# Generated by Django 4.0.3 on 2023-04-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='status_code',
            field=models.CharField(default='PENDING', max_length=12),
        ),
    ]
