# Generated by Django 4.0.3 on 2022-10-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0002_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.AddField(
            model_name='bus',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
