# Generated by Django 4.0.3 on 2023-04-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0002_alter_carrier_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='status_code',
            field=models.CharField(choices=[('APPROVE', 'Approve'), ('NOT APPROVE', 'Notapprove'), ('PENDING', 'Pending')], default='PENDING', max_length=12),
        ),
    ]
