# Generated by Django 4.0.3 on 2023-03-31 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0004_bus_numberplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='busModel',
        ),
    ]
