version: "3.9"
services:
  db:
    container_name: Bus_webapp
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql:delegated
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASS}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_PASSWORD=${DATABASE_PASS}
    ports:
      - "3396:3306"

  server:
    build:
      context: .
    image: tmdt/server
    container_name: web-server
    env_file: .env
    volumes:
      - ./:/app
    ports:
      - ${HOST_SERVER_PORT}:8000
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASS=${DATABASE_PASS}
    command: ["python", "AppApis/app/manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - db
    tty: true

volumes:
  mysql_data:
  python_packages:



#docker compose exec server python ./AppApis/app/manage.py createsuperuser
